Item/urls.py
from django.contrib import admin
from django.urls import path,include
from Item.views import *
from . import views

app_name='Item'

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('',include(core.urls))
    path('<int:pk>',views.detail,name='detail'),
    path('delete/<int:pk>',views.deleteItem,name='delete'),
    path('newItem',views.newItem,name="newItem"),
    path('edit/<int:pk>',views.edit,name="edit"),
    # path('item/',views.item,name='item'),
    path('item/',views.listItems,name='listItems'),

    path('api/listItemsapi/', views.listItemsApi, name="listItemsapi"),
    path('api/suggestionapi/', views.suggestionApi, name="suggestionapi"),
]

OnlineMarketPlace/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('Item/',include('Item.urls')),
    path('Dashboard/',include('dashboard.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import *
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('',include(core.urls))
    path('',index.as_view(),name='index'),
    path('cart',cart.as_view(),name='cart'),
    path('contact/',views.contact,name='contact'),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/',Login.as_view(),name='Login'),
    # path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    path('Logout/',views.Logout,name='Logout'),

]

dashboard/urls.py
from django.contrib import admin
from django.urls import path,include
# from core.views import *
from . import views
from .views import *
from django.contrib.auth import views as auth_views
from django.urls import path
# from .forms import *
from middleware import *


app_name='dashboard'

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('',include(core.urls))
    path('',views.Dashboard,name='Dashboard'),
    path("razorpaycheck/",views.razorpaycheck,name='razorpaycheck'),
    path('CheckOut',CheckOut.as_view(),name='CheckOut'),
    path('myOrders/',views.myOrders,name='myOrders'),
    path('myOrders/',auth_middleware(views.myOrders),name='myOrders')
    # path('contact/',views.contact,name='contact'),
    # path('signup/',views.signup,name='signup'),
    # path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login')

]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,AbstractBaseUser
from .manager import *

from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone

from multiselectfield import MultiSelectField

# Create your models here.
class CustomUser(AbstractBaseUser,PermissionsMixin):

    # username=None
    email=models.EmailField(unique=True)     
    #  class attributes ->
    Name=models.CharField(max_length=100,blank=True)
    # lastlogin=models.DateTimeField()   already in AbstractBaseUser
    date_joined=models.DateTimeField(default=timezone.now)
    is_staff =models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)

    type=(
        (1,"Seller"),
        (2,"Customer")
    )
    # default_type=2

    
    default_type=2
    # user_type=models.IntegerField(choices=type,default=root)
    user_type=MultiSelectField(choices=type,
                                 default=[],
                                 null=True,blank=True)
    

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=[] 

    objects=CustomUserManager()

    def __str__(self):
        return self.Name

    def save(self,*args,**kwargs):
        if not self.id:
            # self.user_type=self.default_type

            self.user_type.append(self.default_type)
        
        return super().save(*args,**kwargs)


class CustomerManager(models.Manager):
    def get_queryset(self,*args,**kwargs):
        return super().get_queryset(*args,**kwargs).filter(Q(user_type__contains=CustomUser.default_type))
            
            # user_type=2)



class SellerManager(models.Manager):
    def get_queryset(self,*args,**kwargs):
        return super().get_queryset(*args,**kwargs).filter(Q(user_type__contains=CustomUser.default_type))




class Customer(CustomUser):
    # CustomUser.user_type=2
    # user_type=CustomUser.user_type
    default_type=2
    
    objects=CustomerManager()

    class Meta:
        proxy=True

    @property
    def showAdditional(self):
        return self.customeradditional
    



    # user=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    # address=models.CharField(max_length=150)
# 

class Seller(CustomUser):
    # CustomUser.user_type=1
    # user_type=CustomUser.user_type
    default_type=1
    
    objects=SellerManager()

    class Meta:
        proxy=True

    @property
    def showAdditional(self):
        return self.selleradditional






class CustomerAdditional(models.Model):
    user=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    address=models.CharField(max_length=100)

class SellerAdditional(models.Model):
    user=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    gst=models.CharField(max_length=10)
    warehouse=models.CharField(max_length=100)

core/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,AuthenticationForm

from .models import *
from django import forms
from django.forms.widgets import PasswordInput
# from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email","Name","password1","password2")



# class LoginForm(AuthenticationForm):
#     username=forms.CharField()
#     password=forms.CharField(widget=PasswordInput())

#     class Meta:
#         model = User
#         # fields = ("email","first_name","last_name","phone",)
#         fields = ('username','password')

core/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from Item.models import Category,Item
from Item.views import get_items_by_ids

from .forms import *
from .models import *
from django.views import View
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate, login
from .decorators import * 
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import CreateView
from django.urls import reverse_lazy


# User=get_user_model()

 

class cart(View):

    def get(self,request):
        if request.session.get('cart'):

            ids=list(request.session.get('cart').keys())
            items=get_items_by_ids(ids)
        # print(items)
        else:
            items={}

        
        return render(request,'core/cart.html',{'items':items})

    def post(self,request):
        item=request.POST.get('item')
        remove=request.POST.get('remove')
        cart=request.session.get('cart')
        

        if remove:
            print(item,cart,type(item))
            if cart[str(remove)]==1:
                cart.pop(str(remove))
            else:
                cart[str(remove)]-=1
        else:

            if cart:
                if item in cart:
                    cart[item]+=1 
                else:
                    cart[item]=1 
            else:
                cart={}
                cart[item]=1

        print(cart)

        request.session['cart']=cart 
        return redirect('cart')







# Create your views here.

class index(View):
    def post(self,request):
        item=request.POST.get('item')
        remove=request.POST.get('remove')
        cart=request.session.get('cart')
        # print(request.user.groups.all.0.name,"Check")
        

        if remove:
            print(item,cart,type(item))
            if cart[str(remove)]==1:
                cart.pop(str(remove))
            else:
                cart[str(remove)]-=1
        else:

            if cart:
                if item in cart:
                    cart[item]+=1 
                else:
                    cart[item]=1 
            else:
                cart={}
                cart[item]=1

        print(cart)

        request.session['cart']=cart 
        return redirect('index')


        


    def get(self,request):
        query=request.GET.get('query','')
        category_id=request.GET.get('category',0)
        # category_id=request.GET['category']
        

        categories=Category.objects.all()

        items=Item.objects.filter(is_sold=False)

        if category_id:
            print("CHeck")
            items=items.filter(category_id=category_id)

        if query:
            items=items.filter(Q(name__icontains=query)| Q(description__icontains=query))


        

        # items=Item.objects.filter(is_sold=False)[0:6]
        print(items)
        categories=Category.objects.all()
        print(categories)
        # context={ categories :'categories',
        # items :'items'}
        # for item in items:
        #     print(item.name)
        #     print(item.price)

        return render(request,'core/index.html',{'items':items,'categories':categories})

# def index(request):
    

def contact(request):
    return render(request, 'core/contact.html')



class SignUpView(CreateView):
    form_class = SignUpForm
    model = CustomUser
    template_name='core/SignUp.html'
    success_url = reverse_lazy('Login') 


class Login(LoginView):
    # form_class=LoginForm 
    # model=CustomUser 
    template_name='core/login.html'
    success_url=reverse_lazy('index') 

# class Logout(LogoutView):
#     success_url=reverse_lazy('index') 

# def signup(request):
#     form=SignupForm()

#     if request.method=='POST':

#         form=SignupForm(request.POST)
#         if form.is_valid():
#             user=form.save()
#             # Customer.objects.create(user=user,first_name=user.first_name,last_name=user.last_name,email=user.email,phone=user.phone,)

#             return redirect('login')
#     msg=False


#     context={'form':form,'msg':msg}
#     # return render(request)

#     # return HttpResponse('This is Homepage')
#     return render(request,'core/signup.html',context=context)


# @unauthenticated_user
# def login(request):
<<<<<<< HEAD
<<<<<<< HEAD
#     # returnUrl=request.GET.get('return_url')        
=======
<<<<<<< HEAD
=======
>>>>>>> 0a486ef787fe078b7cad44a4746176e32bb45294
#     # returnUrl=request.GET.get('return_url')
=======
#     # returnUrl=request.GET.get('return_url')          -------- land with the same earlier url which was before after login 
>>>>>>> main
<<<<<<< HEAD
>>>>>>> 0a486ef787fe078b7cad44a4746176e32bb45294
=======
>>>>>>> 0a486ef787fe078b7cad44a4746176e32bb45294
#     if request.method=="POST":
#         # name=request.POST.get('name')
#         username=request.POST.get('username')
#         password=request.POST.get('password')
#         # password2=request.POST.get('password2')

#         user = auth.authenticate(username=username, password=password)
#         if user is not None:
#             auth.login(request, user)
#             # messages.info(request,'Welcome')
#             # if returnUrl :
#             #     return HttpResponseRedirect(returnUrl)
                
#             # else:
#                 # returnurl=None
#             return redirect("index")

#             # Redirect to a success page.
        
#         else:

#             # messages.info(request,'Invalid Credentials')
#             return render(request,'core/login.html')

#     # return HttpResponse('This is about Page')
#     else:
#         # return render(request,'about.html')
#         return render(request,'core/login.html')

#     # return HttpResponse('This is Login page')
#     # return render(request,'index.html')
#     # return render(request,'core/login.html')


def Logout(request):
    request.session.clear()
    auth.logout(request)
    print("logout")



    return redirect('index')

#     return redirect('login')


# @login_required(login_url='Login')
# def Logout(request):
    
#     return redirect('Home')

    

templates/core/HomePage.html
{% extends 'core/base.html' %}

{% load cart %}

{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container fluid mt-3">

        


       
        <div class="row">

            <div class=" col-lg-3 mx-auto">
                <div class="list-group list-group flush" style="width: 18rem;">
                    {% for category in categories %}
                    <a href="/?category={{category.id}}" class="list-group_item list-group-item-action ">{{category.name}}</a>
                    <!-- <p class="">{{category.items.count}}</p> -->

                    {% endfor %}
                </div>
            </div>
             <!-- all items -->

           
                <div id="items " class="col lg-8" >
                    <div class="row mx-auto">
                        {% for item in items %}
                        <div class="card mx-auto mb-3" style="width: 18rem;">
                            <a href="{% url 'Item:detail' item.id %}">
                            
                                <img src="{{ item.image.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <h5 class="card-title">{{item.name}}</h5>
                                  <p class="card-text">{{item.price}}</p>
    
                                  <div class="card-footer p-0 no-gutters ">
                                    {% if item|is_in_cart:request.session.cart %}
                                        <div class="row no-gutters">
                                            <form action="/#{{item.id}}" class="col-2" id="{{item.id}}" method="post">
                                                {% csrf_token %}
                                                <input hidden type="number" name="remove"  value="{{item.id}}">
                                                <input type="submit" value=" - " class=" col-2 btn btn-block btn-secondary">
                                            </form>
                                            <div class="text-center col">{{item|quantity_in_cart:request.session.cart}} in cart</div>
                                            <form action="/#{{item.id}}" class="col-2" id="{{item.id}}" method="post">
                                                {% csrf_token %}
                                                <input hidden type="text" name="item" value="{{item.id}}">
                                                <input type="submit" value=" + " class=" col-2 btn btn-block btn-secondary">
        
                                            </form>
                                        </div>
                                    {% else %}   
                                        <form action="/#{{item.id}}" method="POST" class="btn-block" id="{{item.id}}"">
                                            {% csrf_token %}                         
                                            <input hidden type="text" name="item" value="{{item.id}}">
                                            <input type="submit" class="float-right btn btn-light border btn-sm form-control"  value="Add to Cart"> 
                                        </form>
                                    {% endif %}  
    
                                  <!-- <a href="#" class="btn btn-light border btn-sm">Add to Cart</a> -->
                                </div>
                            </a>
                            

                            
                        

                        


                        </div>
                        {% endfor %}
                        
                    </div>
                    
    
                </div>

            
             
            
        </div>
        
    </div>
    

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>
{% endblock %}

templates/core/base.html
{% load static %}

{% load cart %}
{% load extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    

    <nav class=" py-6 px-6 flex item-center justify-between border-b border-gray-200">

        <div><a href="/" class="text-xl  font-semibold">Purtune</a></div>
        
        
        
        <div class="ml-auto space-x-6">
            <a href="{% url 'Item:listItems' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700 ">Browse</a>
            
            
            <a href="{% url 'cart' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Cart
                <span class="badge badge-info">{{request.session.cart.values|sumCart}}</span>

            </a>

            {% if user.is_authenticated %}
                
                {% if user.groups.all.0.name == "admin" %} 
                    <a href="{% url 'Item:newItem' %}" class=" px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700 ">New Item</a> 
                    <a href="{% url 'dashboard:Dashboard' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">DashBoard</a>       
                {% endif %}
                <a href="{% url 'dashboard:myOrders' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Orders</a>
                <a href="{% url 'Logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
                

            {% else %}
                <a href="{% url 'signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Signup</a>
                <a href="{% url 'Login' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Login</a>
                
            {% endif %}
        </div>
        <div>
            
          
        </div>
    </nav>

    {% block css%}
    {% endblock %}

    {% block js %}

    {% endblock %}



    <div class="px-6 py-3 ">
        {% block content %}

        {% endblock %}
    </div>



    
        


    <footer class="py-6 px-6 flex justigy between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb -5 font semibold text gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde esse voluptas cum illum consectetur nihil, consequatur soluta rem quas nobis a suscipit veniam odit blanditiis quasi quaerat vero, tenetur quisquam!</p>

        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of Use</a></li>
            </ul>
        </div>
    </footer>
    
</body>
</html>

{% block scripts %}

{% endblock scripts %}

{% comment %} Razorpay checkout {% endcomment %}

<!-- <script src="static/check.js"></script> -->

templates/core/cart.html
{% extends 'core/base.html' %}
{% load cart %}
{% load custom_filter %}
{% block content %}



Cart 
  

<div class="container">
    <div class="border rounded p-4 m-4">
        <table class="table table-light table">
            <thead class="table-light">
        
                <tr>
                    <th scope="col">S NO</th>
                    <th scope="col">Item </th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                    
        
                   
                </tr>
            </thead>

            {% if not user.is_authenticated %}

                
                <tr> <h2 class="" >Please Login to View your Cart details  </h2></tr>

            {% else %}
        
            {% for item in items %}
        
        
                <tr>
                    <td>{{forloop.counter1}}</td>
                    <td><img style="height:80px" class="rounded-circle" src="{{ item.image.url }}" alt="not loading "></td>
<<<<<<< HEAD
                    <td> {{item.name}}</td>
=======
                    <!-- <td> {{item.name}}</td> -->
>>>>>>> main
                    <td> {{item.price|currency }}</td>
                    <td> {{item|quantity_in_cart:request.session.cart}}</td>
                    <td> {{item|price_total:request.session.cart | currency }}</td>
                    <td>
                        <div class="row no-gutters">
                            <form  action="{% url 'cart' %}" id="{{item.id}}" method="post">
                                {% csrf_token %}
                                <input hidden type="number" name="remove"  value="{{item.id}}">
                                <input type="submit" value=" - " class=" col-2 btn btn-block btn-secondary">
                            </form>
                            <div class="text-center col">{{item|quantity_in_cart:request.session.cart}} in cart</div>
                            <form action="{% url 'cart'  %}"  method="post">
                                {% csrf_token %}
                                <input hidden type="text" name="item" value="{{item.id}}">
                                <input type="submit" value=" + " class=" col-2 btn btn-block btn-secondary">

                            </form>
                        </div>
                    </td>
                    
                   
                </tr>
        
                
        
            {% endfor %}
            


            <tfoot>
                {% if request.session.cart %}
                <tr>
                    <th colspan="4">Total</th>
                    <th>{{items|cart_total_price:request.session.cart}}</th>
    
    
                </tr>
                {% else %}
                <tr>
                    <h2 class="" >No Items in Cart please checkout products <a href="{% url 'index' %}"> here </a>  </h2>


                </tr>
                
                {% endif %}
            </tfoot>
            {% endif %}
        
        </table> 
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


        {% if user.is_authenticated %}
        
        <div class="m-3 p-3">
            <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-outline-info border rounded col-lg-13 float-right">Check Out</a>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Check out form </h5>
                    <hr>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="m-2 p-3">
                        <form action="{% url 'dashboard:CheckOut' %}" method="POST">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="Fname"></label>
                                <input type="text" name="Fname" id="" class="form-control" placeholder="first name" aria-describedby="helpId">
                            </div>
                            <div class="form-group">
                                <label for="Lname"></label>
                                <input type="text" name="Lname" id="" class="form-control" placeholder="last name" aria-describedby="helpId">
                            </div>
                            <div class="form-group">
                                <label for="Phone"></label>
                                <input type="text" name="Phone" id="" class="form-control" placeholder="Phone" aria-describedby="helpId">
                            </div>
                            <div class="form-group">
                                <label for="Address"></label>
                                <input type="text" name="Address" id="" class="form-control" placeholder="Address" aria-describedby="helpId">
                            </div>
                            <div class="form-group">
                                <label for="City"></label>
                                <input type="text" name="City" id="" class="form-control" placeholder="City" aria-describedby="helpId">
                            </div>
                            <div class="form-group">
                                <label for="State"></label>
                                <input type="text" name="State" id="" class="form-control" placeholder="State" aria-describedby="helpId">
                            </div>
                            <div class="form-group">
                                <label for="Pincode"></label>
                                <input type="text" name="Pincode" id="" class="form-control" placeholder="Pincode" aria-describedby="helpId">
                            </div>
                            

                            
                            <button type="button" class="btn btn-primary payWithRazorpay w-100 mt-2">Pay with Razorpay </button>
                            
                            <!-- <a href="{% url 'dashboard:myOrders' %}">
                                <button type="button" class="float-right btn bgn-outline-info col=lg-6">Orders</button>
                            </a> -->
                              
                            

                            <!-- <a href=""></a> -->
                        </form>
                        
                    </div>
                ...
                </div>
                
            
        </div>
        {% endif %}
        {% if messages %}
        
        <div class="alert alert-success {{ message.tags }} mx-3 mb-0" role="alert">
            <h4 class="alert-heading">{{messages}}</h4>
            <p class="mx-0 mb=0 my=0 py=0"></p>

        </div>
        
        {% endif %}
        <!-- Button trigger modal -->

    </div>
            

</div>
{% endblock %}

{% block scripts %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="static/check.js"></script>
{% endblock scripts  %}

templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
    HomePage 
{% endblock %}


{% block content %}
This is Contact Page
{% endblock %}

templates/core/login.html
{% extends 'core/base.html '%}

{% block content %}
<div class="flex justify-center items-center min-h-screen"> <!-- Center the form both vertically and horizontally -->
    <div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-md "> <!-- Adjust background, padding, and max width -->

        <!-- <div class="form-layout"> -->
        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{ form.non_field_errors}}
            
            <h2 class="mb-12 text-2xl text-center">Login</h2>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{form.username}}
            </div>  
            <!-- <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{form.email}}
            </div>  -->
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password}}
                <!-- {{form.password}} -->
            </div>  
            <!-- <div class="mb-3">
                <label class="inline-block mb-2">Password2</label><br>
                {{form.password2}}
            </div> -->

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors }}

                    {% endfor %}
                </div>
            {% endif %}
    




            

            <button type="submit" class="mt-6 w-full px-6 py-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Login</button>
        </form>
        <!-- </div> -->
    </div>
</div>

</body>
</html>
{% endblock %}