Item/urls.py
from django.contrib import admin
from django.urls import path,include
from Item.views import *
from . import views

app_name='Item'

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('',include(core.urls))
    path('<int:pk>',views.detail,name='detail'),
    path('delete/<int:pk>',views.deleteItem,name='delete'),
    path('newItem',views.newItem,name="newItem"),
    path('edit/<int:pk>',views.edit,name="edit"),
    # path('item/',views.item,name='item'),
    path('item/',views.listItems,name='listItems'),

    path('api/listItemsapi/', views.listItemsApi, name="listItemsapi"),
    path('api/suggestionapi/', views.suggestionApi, name="suggestionapi"),
]

OnlineMarketPlace/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('Item/',include('Item.urls')),
    path('Dashboard/',include('dashboard.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Item/models.py
from django.db import models
from core.models import CustomUser

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Item(models.Model):
    category=models.ForeignKey(Category,related_name="items",on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=500)
    price=models.FloatField()
    image=models.ImageField(upload_to="items_images",blank=True,null=True)
    is_sold=models.BooleanField(default=False)
    created_by=models.ForeignKey(CustomUser,related_name='items',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Item/forms.py
from .models import *
from django import forms 


INPUT_CLASSES='w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model=Item 
        fields=['category','name','description','price','image',]


class EditItemForm(forms.ModelForm):
    class Meta:
        model=Item 
        fields=['category','name','description','price','image','is_sold']
        widgets={
            'category':forms.Select(attrs={
                'class':INPUT_CLASSES 
            }),
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES 
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES 
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES 
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            })
        }

Item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Item 
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from core.decorators import *

from django.views.generic import TemplateView, FormView, CreateView, ListView, UpdateView, DeleteView, DetailView, View
# Create your views here.
# 
# 
# grid grid-cols-3 gap-3


def item(request):
    if request.method=="GET":
        query=request.GET.get('query','')
        category_id=request.GET.get('category',0)
        categories=Category.objects.all()

        print(category_id,type(category_id))
        

        items=Item.objects.filter(is_sold=False)
       

        if category_id:
            
            items=items.filter(category_id=category_id)
            print(items)

        if query:
            items=items.filter(Q(name__icontains=query)| Q(description__icontains=query))


    context={'items':items ,'query':query,'categories':categories,'category_id':int(category_id)}
    return render(request,'Item/item.html',context)  



class ListItems(ListView):
    template_name = "item/item1..html"
    model = Item
    context_object_name = "item"
    paginate_by = 2



from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.http import JsonResponse
ITEMS_PER_PAGE = 3
def listItems(request):
    
    ordering = request.GET.get('ordering', "")     # http://www.wondershop.in:8000/listproducts/?page=1&ordering=price
    search = request.GET.get('query', "")
    price = request.GET.get('price', "")
    category_id=request.GET.get('category',0)
    categories=Category.objects.all()


    if search:
        item = Item.objects.filter(Q(name__icontains=search) )    #| Q(category__contains=search)) # SQLite doesn’t support case-sensitive LIKE statements; contains acts like icontains for SQLite

    else:
        item = Item.objects.all()

    if ordering:
        item = item.order_by(ordering) 

    if price:
        item = item.filter(price__lt = price)

    if category_id:
            
            item=item.filter(category_id=category_id)
            # print(items)


    
    

    # Pagination
    page = request.GET.get('page',1)
    item_paginator = Paginator(item, ITEMS_PER_PAGE)
    try:
        item = item_paginator.page(page)
    except EmptyPage:
        item = item_paginator.page(item_paginator.num_pages)
    except:
        item = item_paginator.page(ITEMS_PER_PAGE)
    return render(request, "Item/item4.html", {"items":item, 'page_obj':item, 'is_paginated':True, 'paginator':item_paginator,'categories':categories,'category_id':int(category_id),'query':search}) 


def suggestionApi(request):
    if 'term' in request.GET:
        search = request.GET.get('term')
        qs = Item.objects.filter(Q(name__icontains=search))[0:10]
        # print(list(qs.values()))
        # print(json.dumps(list(qs.values()), cls = DjangoJSONEncoder))
        titles = list()
        for item in qs:
            titles.append(item.name)
        #print(titles)
        # if len(qs)<10:
        #     length = 10 - len(qs)
        #     qs2 = Item.objects.filter(Q(category__icontains=search))[0:length]
        #     for item in qs2:
        #         titles.append(item.category)
        return JsonResponse(titles, safe=False)      # [1,2,3,4] ---> "[1,2,3,4]"   queryset ---> serialize into list or dict format ---> json format using json.dumps with a DjangoJSONEncoder(encoder to handle datetime like objects)




def listItemsApi(request):
    # print(Product.objects.all())
    # print(Product.objects.values())
    #result = json.dumps(list(Product.objects.values()), sort_keys=False, indent=0, cls=DjangoJSONEncoder)   # will return error if you have a datetime object as it is not jsonserializable  so thats why use DjangoJSONEncoder, indent to beautify and sort_keys to sort keys
    #print(type(result))    #str type  
    #print(result)
    result = list(Item.objects.values())          # will work like passing queryset as a context data if used by a template
    #print(result)
    #return render(request, "firstapp/listproducts.html", {"product":result})
    return JsonResponse(result, safe=False)






def get_items_by_ids(ids):
    return Item.objects.filter(id__in=ids)

    

def detail(request,pk):
    item=get_object_or_404(Item,pk=pk)
    related_Items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:6]
    context={'item': item,'related_Items': related_Items}

    return render(request,'Item/detail.html',context)





@login_required(login_url='login')
@allowed_users(allowed_roles=['admin','Developer'])
def deleteItem(request,pk):
    item=get_object_or_404(Item,pk=pk)
    cart=request.session.get('cart')
    if str(item.id) in cart:
        # cart=request.session.get('cart')
        cart.pop(str(item.id))
        request.session['cart'] = cart
        print("Popped Out")

    print(cart)

    item.delete()
    return render(request,"core/index.html")

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin','Developer'])
def edit(request,pk):
    item=get_object_or_404(Item,pk=pk)
   
    if request.method=='POST':
        form=EditItemForm(request.POST,request.FILES,instance=item)
        if form.is_valid():
            item=form.save()
        # item.created_by

            return redirect('Item:detail',pk=item.id)
    else:
        form=EditItemForm(instance=item)
        context={'form':form,'title': 'Edit Items ','instance':item}
    # return render(request)



    # return HttpResponse('This is Homepage')
    return render(request,'Item/form.html',context=context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin','Developer'])
def newItem(request):
    form=NewItemForm()
    print("*")
    if request.method=='POST':
        form=NewItemForm(request.POST,request.FILES)
        print("**")
        if form.is_valid():
            print("II")
            item=form.save(commit=False)
            item.created_by=request.user
            print("itemname",item.name)
            item.save()
            return redirect('Item:detail',pk=item.id)

    context={'form':form,'title': 'Add NewItems '}
    # return render(request)



    # return HttpResponse('This is Homepage')
    return render(request,'Item/form.html',context=context)

templates/Item/detail.html
{% extends 'core/base.html' %}

{% block title %}
    {{ item.name }}
{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <!-- Adjust the image size and containment -->
        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-xl w-full h-96 object-contain">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl font-semibold">{{ item.name }}</h1>
        <p class="text-gray-500 mb-4"><strong>Price:</strong> {{ item.price }}</p>
        <p class="text-gray-500 mb-4"><strong>Seller:</strong> {{ item.created_by }}</p>

        {% if item.description %} 
            <p class="text-gray-700 mb-6">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }} 
            </p>
        {% endif %} 

        <div class="flex space-x-4">
            {% if request.user == item.created_by %}
                <a href="{% url 'Item:delete' item.id %}" class="inline-block px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Delete</a>
                <a href="{% url 'Item:edit' item.id %}" class="inline-block px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Edit</a>
            {% else %}
                <a href="#" class="inline-block px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
                <form action="{% url 'cart' %}" method="POST" class="inline-block">
                    {% csrf_token %}
                    <input hidden type="text" name="item" value="{{ item.id }}">
                    <input type="submit" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" value="Add to Cart">
                </form>
            {% endif %}
        </div>
    </div>
</div>

<div class="mt-12 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items</h2>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for item in related_Items %}
            <div class="bg-white rounded-xl overflow-hidden shadow-lg">
                <a href="{% url 'Item:detail' item.id %}">
                    <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full h-48 object-contain rounded-t-xl">

                    <div class="p-6">
                        <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                        <p class="text-gray-500 mt-2">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/Item/form.html
{% extends 'core/base.html' %}  

{% block title %}{{title}} {% endblock  %}

{% block content %}
<h1 class="mb-9 text-3xl text-center">{{title}}</h1>

<div class="flex justify-center items-center ">
    <div class="  bg-white rounded-lg shadow-lg w-full max-w-lg min-h-screen">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- <h2 class="mb-4 text-2xl text-center">Form Title</h2> -->

            <div class="mb-2">
                <label class="block text-lg font-medium text-gray-700 mb-2">{{ form.as_p }}</label>
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
            </div>
            {% endif %}

            <button type="submit" class="w-full px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Submit</button>
        </form>
    </div>
</div>







{% endblock %}

templates/Item/item.html
{% extends 'core/base.html' %}

{% block title %}Items {% endblock %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">
<<<<<<< HEAD

        <!-- <form method="get" action="{% url 'Item:item' %}"> -->

=======
<<<<<<< HEAD
        <form method="get" action="{% url 'Item:item' %}">
=======
>>>>>>> 0a486ef787fe078b7cad44a4746176e32bb45294
        <form method="get" action="{% url 'Item:listItems' %}">
>>>>>>> main
            <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair">
            <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
        </form>

        <hr class="my-6">
        <p class="font-semibold">Categories</p>
        <ul>
            {% for category in categories %}
                <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                    <a href="{% url 'Item:item' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr class="my-6">
        <p class="font-semibold">Clear Filter</p>
        <ul>
            <li><a href="{% url 'Item:item' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
        </ul>
    </div>

    <div class="col-span-3 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
        {% for item in items %}
            <div class="bg-white rounded-xl shadow-lg overflow-hidden flex flex-col">
                <a href="{% url 'Item:detail' item.id %}">
                    <!-- Adjust image size and aspect ratio -->
                    <div class="w-full h-56 bg-gray-200 flex items-center justify-center">
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="max-w-full max-h-full object-contain rounded-t-xl">
                    </div>
                    <div class="p-4 flex flex-col">
                        <h2 class="text-xl font-semibold mb-2">{{ item.name }}</h2>
                        <p class="text-gray-500 mb-2">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======

    
>>>>>>> main
>>>>>>> 0a486ef787fe078b7cad44a4746176e32bb45294
</div>
{% endblock %}

templates/Item/item4.html
{% extends 'core/base.html' %}

{% load extras %}

{% block title %}Items{% endblock %}

{% block css %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>
  .main-area {
    padding-left: 20px;
    padding-right: 20px;
    padding-top: 0px;
    background-color: #f8f9fa;
  }

  .product-cards {
    height: 50;
    background-color: white;
    padding: 2px;
  }

  .btn-primary {
    margin: 10px;
  }



  .pagination {
    justify-content: center;
    margin-top: 20px;
  }

  .utility {
    display: flex;
  }
  
  .filter-btn, .sort-btn, .clear-btn {
    display: block;
    padding: 10px;
    margin: 10px 0;
    background-color: #38b2ac;
    color: white;
    border-radius: 5px;
    text-align: center;
    transition: background-color 0.2s ease-in-out;
  }
  .filter-btn:hover, .sort-btn:hover, .clear-btn:hover {
    background-color: #2c7a7b;
  }

  .product-card {
    background-color: white;
    border-radius: 12px;
    height:auto;
    overflow: hidden;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    margin-bottom: 10px;
  }

 
  .product-card:hover {
    transform: translateY(-10px);
  }

  .pagination {
    display: flex;
    justify-content: center;
  }
  .pagination li {
    margin: 0 5px;
  }
  .pagination a {
   
    padding: 8px 12px;
    border-radius: 5px;
    background-color: #38b2ac;
    color: white;
    text-decoration: none;
    transition: background-color 0.2s ease-in-out;
  }
  .pagination a:hover {
    background-color: #2c7a7b;
  }
  .pagination .active a {
    background-color: #2c7a7b;
    font-weight: bold;
  }


   
      


  
  
</style>


{% endblock %}

{% block js %}
<script>
  // Get sorting and price filters to display in dropdown
  function get(name) {
    if (name = (new RegExp('[?&]' + encodeURIComponent(name) + '=([^&]*)')).exec(location.search))
      return decodeURIComponent(name[1]);
  }

  if (get('ordering')) {
    document.getElementById('placeholder').innerHTML = "Sort: " + document.getElementById(get('ordering')).innerHTML;
  }

  if (get('price')) {
    document.getElementById('price-placeholder').innerHTML = "Price: " + document.getElementById('pr' + get('price')).innerHTML;
  }

  // Get URL with ordering applied
  function finalurl() {
    var url = new URL(window.location.href);
    var search_params = url.searchParams;
    search_params.set('ordering', document.getElementById("sort-list").value);
    url.search = search_params.toString();
    return url.toString();
  }

  // Get URL with price filtering
  function finalurl2() {
    var url = new URL(window.location.href);
    var search_params = url.searchParams;
    search_params.set('price', document.getElementById("price-list").value);
    url.search = search_params.toString();
    return url.toString();
  }
</script>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  // Auto-suggestions for search
  $(function () {
    $("#query").autocomplete({
      source: "{% url 'Item:suggestionapi' %}",
      minLength: 2
    });
  });
</script>
{% endblock %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">
        <form method="get" action="{% url 'Item:listItems' %}">
            <input name="query" class="w-full py-4 px-6 border rounded-xl focus:outline-none focus:ring-2 focus:ring-teal-400" type="text" id="query" value="{{ query }}" placeholder="Search for a product...">
            <button class="filter-btn">Search</button>
        </form>

        <!-- Price filter dropdown -->
        <select name="price" id="price-list" onchange="location=finalurl2();" class="w-full py-2 px-4 border rounded-xl focus:outline-none focus:ring-2 focus:ring-teal-400">
          <option value="" id="price-placeholder" disabled selected hidden>Price</option>
          <option id="pr500" value="500">less than 500</option>
          <option id="pr1000" value="1000">less than 1000</option>
          <option id="pr2000" value="2000">less than 2000</option>
          <option id="pr10000" value="10000">less than 10000</option>
        </select>

        <!-- Sort functionality -->
        <select name="sort" id="sort-list" onchange="location=finalurl();" class="w-full py-2 px-4 border rounded-xl focus:outline-none focus:ring-2 focus:ring-teal-400 mt-4">
          <option value="" id="placeholder" disabled selected hidden>Sort</option>
          <option id="price" value="price">Price: Low To High</option>
          <option id="-price" value="-price">Price: High To Low</option>
          <option id="product_name" value="name">Product Name</option>
          <option id="-date_added" value="-created_at">What's New</option>
        </select>

        <hr class="my-6">
        <p class="font-semibold">Categories</p>
        <ul>
            {% for category in categories %}
                <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                    <a href="{% url 'Item:listItems' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr class="my-6">
        <p class="font-semibold">Clear Filter</p>
        <a href="{% url 'Item:listItems' %}" class="clear-btn">Clear Filters</a>
    </div>

    <!-- Product Cards Section -->

    <div class="col-span-3 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 h-">
        {% for item in items %}
            <div class="product-card w-full h-66 ">
                <a href="{% url 'Item:detail' item.id %}">
                    <div class="w-full h-56 bg-gray-200 flex items-center justify-center">
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="max-w-full max-h-full object-contain rounded-t-xl">
                    </div>
                    <div class="p-4 flex flex-col">
                        <h2 class="text-xl font-semibold mb-1">{{ item.name }}</h2>
                        <p class="text-gray-20 ">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div> 

    
    <br>

    <!-- Pagination -->
    {% if is_paginated %}
    <nav class="pagination">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="/Item/item/?page={{ page_obj.previous_page_number }}&{{ request.GET.urlencode|safe|cut:'page=' }}">Previous</a>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if i == page_obj.number %}
        <li class="page-item active">
          <a class="page-link" href="/Item/item/?page={{ i }}&{{ request.GET.urlencode|safe|cut:'page=' }}">{{ i }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="/Item/item/?page={{ i }}&{{ request.GET.urlencode|safe|cut:'page=' }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="/Item/item/?page={{ page_obj.next_page_number }}&{{ request.GET.urlencode|safe|cut:'page=' }}">Next</a>
        </li>

        {% endif %}
    {% endif %}

{% endblock %}